language: python
python:
- "3.3"
- "3.4"
- "3.5"

sudo: false
cache: pip

install:
- pip install invoke

script:
- invoke build
- invoke lint

notifications:
  email: false
  irc:
    channels:
    - "chat.freenode.net#pietroalbini"
    template:
    - "Build %{result} for %{repository_slug} on branch %{branch} (%{commit})."
    - "More details: %{build_url}"
    use_notice: true
    skip_join: true
